server:
  port: 8080

# MongoDB Settings
spring:
  data:
    mongodb:
      uri: mongodb://test1:test1234@192.168.35.135:17017/test?authSource=admin&authMechanism=SCRAM-SHA-1
      database: test

#spring:
#  data:
#    mongodb:
#      host: 192.168.35.135
#      port: 17017
#      username: test1
#      password: test1234
#      database: test
#      authentication-database: admin


  # MySQL
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ev_music?useSSL=false
#    username: root
#    password: 1234
#
## MyBatis Settings
#mybatis:
#  config-location: mybatis/mybatis-config.xml
#  mapper-locations: mybatis/mapper/*.xml
